In [1]:
from query_based_search import Prompt_exhibition_generator
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

c:\Users\markt\anaconda3\envs\metaverse_museum\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [2]:
# from sklearn.metrics.pairwise import cosine_similarity

In [3]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [4]:
s1 = 'Van Gogh'
s2 = 'Vincent van Gogh'
embeddings1 = model.encode(s1, convert_to_tensor=True).cpu()
embeddings2 = model.encode(s2, convert_to_tensor=True).cpu()
cosine_similarity([embeddings1], [embeddings2])

c:\Users\markt\anaconda3\envs\metaverse_museum\Lib\site-packages\transformers\models\bert\modeling_bert.py:439: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(


array([[0.9368604]], dtype=float32)

In [12]:
s1 = 'peaceful'
s2 = 'serene'
embeddings1 = model.encode(s1, convert_to_tensor=True).cpu()
embeddings2 = model.encode(s2, convert_to_tensor=True).cpu()
cosine_similarity([embeddings1], [embeddings2])

array([[0.5578123]], dtype=float32)

In [6]:
s1 = 'Self-Portrait'
s2 = 'Self-Portrait with a Straw Hat (obverse: The Potato Peeler)'
embeddings1 = model.encode(s1, convert_to_tensor=True).cpu()
embeddings2 = model.encode(s2, convert_to_tensor=True).cpu()
cosine_similarity([embeddings1], [embeddings2])

array([[0.6415447]], dtype=float32)

In [7]:
# cosine_similarity([[1, 0, -1]], [[1,-1, -2]])[0][0]

In [8]:
agent = Prompt_exhibition_generator()

(12432, 34)


c:\Users\markt\anaconda3\envs\metaverse_museum\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
c:\Users\markt\anaconda3\envs\metaverse_museum\Lib\site-packages\open_clip\factory.py:129: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickl

In [9]:
agent.generate_exhibition("I want to see Van Gogh's use of color")

***Tag extraction time: 0.684149980545044
***Parse time: 0.40509629249572754
***Total time taken to parse the prompt: 1.0892462730407715 seconds
***Total time taken to search: 0.45961809158325195 seconds
***Total time taken to filter the results: 20.521631002426147 seconds
Successfully filtered the results based on tags and artists
**** Getting embeddings of descriptions...
Loading embeddings from file...
**** Getting embeddings of descriptions done. Time taken: 0.006509542465209961 seconds


d:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\exhibition_curator.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.description_embeddings = torch.load(r'D:

***Total time taken to curate the exhibitions: 9.642972707748413 seconds
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see Van Gogh's use of color\Exhibition_0.jpg
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see Van Gogh's use of color\Exhibition_1.jpg
***Total time taken to generate the exhibition: 45.867408752441406 seconds


In [11]:
agent.generate_exhibition("I want to see loneliness and depression")

***Tag extraction time: 0.7548065185546875
***Parse time: 0.4632742404937744
***Total time taken to parse the prompt: 1.218080759048462 seconds
***Total time taken to search: 0.33702540397644043 seconds
***Total time taken to filter the results: 16.078916788101196 seconds
Successfully filtered the results based on tags and artists
**** Getting embeddings of descriptions...
Loading embeddings from file...
**** Getting embeddings of descriptions done. Time taken: 0.008946895599365234 seconds


d:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\exhibition_curator.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.description_embeddings = torch.load(r'D:

***Total time taken to curate the exhibitions: 30.05069851875305 seconds
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see loneliness and depression\Exhibition_0.jpg
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see loneliness and depression\Exhibition_1.jpg
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see loneliness and depression\Exhibition_2.jpg
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see loneliness and depression\Exhibition_3.jpg
Image saved as D:\Metaverse_Museum\AI-Curators\prompt_based_exhibition\output\I want to see loneliness and depression\Exhibition_4.jpg
***Total time taken to generate the exhibition: 69.42788553237915 seconds
